#!/usr/bin/env bash

set -xeuo pipefail

TARGET=$1

install -Dm644 10-emergency-lock.rules -t ${TARGET}/usr/lib/udev/rules.d
install -Dm755 emergency-lock-on-add -t ${TARGET}/usr/bin
install -Dm755 emergency-lock-on-remove -t ${TARGET}/usr/bin
