#!/usr/bin/env bash

set -uexo pipefail

sed -i 's|#LockLayering.*|LockLayering=true|' /etc/rpm-ostreed.conf

systemctl disable bootc-fetch-apply-updates.timer
systemctl mask bootc-fetch-apply-updates.timer
systemctl disable rpm-ostreed-automatic.timer
systemctl mask rpm-ostreed-automatic.timer

sed -i 's|DefaultZone=.*|DefaultZone=public|' /etc/firewalld/firewalld.conf

dnf -y install \
    alacritty \
    gnome-system-monitor \
    virt-manager

dnf -y install \
    eza \
    fastfetch \
    neovim \
    tmux \
    vim

dnf -y install \
    niri \
    fuzzel \
    brightnessctl \
    lisgd \
    mako \
    quickshell \
    stevia \
    swaybg \
    swayidle \
    waybar \
    wl-kbptr \
    xwayland-satellite

dnf -y install just bcvk podman buildah

dnf -y install gcc kernel-devel

dnf -y install yggdrasil
