name: Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-26.04
    permissions:
      packages: write

    env:
      BUILD_REGISTRY: ${{ vars.REGISTRY }}
      BUILD_NAME: aquarium
      BUILD_BRANCH: 44
      BUILD_TAG: 44

    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@695eb75bc387dbcd9685a8e72d23439d8686cba6
        with:
          extra-squeeze: true

      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4

      - name: Pull
        id: pull
        run: just pull

      - name: Build
        id: build
        run: just build

      - name: Login to registry
        env:
          TOKEN: ${{ secrets.REGISTRY_TOKEN }}
          USER: ${{ secrets.REGISTRY_USER }}
        run: |
          echo "${TOKEN}" | podman login -u "${USER}" --password-stdin "${BUILD_REGISTRY}"
          echo "${TOKEN}" | docker login -u "${USER}" --password-stdin "${BUILD_REGISTRY}" # for cosign

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.1.1

      - name: Push to registry
        id: push
        env:
          REGISTRY: ${{ env.BUILD_REGISTRY }}
          IMAGE: ${{ env.BUILD_NAME }}
          TAG: ${{ env.BUILD_TAG }}
        run: |
          set -x
          # HACK: push a second time so layer annotations are present
          # TODO: remove me when https://github.com/containers/podman/issues/27796 fixed
          podman push --digestfile=/tmp/digestfile "$REGISTRY/$IMAGE:$TAG"
          echo "digest=$(< /tmp/digestfile)" | tee "${GITHUB_OUTPUT}"
          podman push --digestfile=/tmp/digestfile "$REGISTRY/$IMAGE:$TAG"
          echo "digest=$(< /tmp/digestfile)" | tee "${GITHUB_OUTPUT}"

      - name: Sign with cosign
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: just sign "${{ steps.push.outputs.digest }}"

